let express=require("express")
let mongoose=require("mongoose")
let app=express()
let cors=require("cors")
const route=require("./routes/userroute")
app.use(express.json())
app.use(cors())
mongoose.connect("mongodb://127.0.0.1:27017/userdbs").then(()=>{
    console.log("ok")
})
app.use("/",route)
app.listen(5000)